channels:
- conda-forge
dependencies:
- python=3.7.11
- pip<=22.3.1
- pip:
  - mlflow
  - cloudpickle==2.1.0
  - dataclasses==0.6
  - pathlib==1.0.1
  - psutil==5.9.4
  - scikit-learn==1.0.2
name: mlflow-env
